# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import config_pb2 as config__pb2


class RedditServiceStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePost = channel.unary_unary(
                '/RedditService/CreatePost',
                request_serializer=config__pb2.Post.SerializeToString,
                response_deserializer=config__pb2.Post.FromString,
                )
        self.VotePost = channel.unary_unary(
                '/RedditService/VotePost',
                request_serializer=config__pb2.VotePostRequest.SerializeToString,
                response_deserializer=config__pb2.Post.FromString,
                )
        self.GetPost = channel.unary_unary(
                '/RedditService/GetPost',
                request_serializer=config__pb2.GetPostRequest.SerializeToString,
                response_deserializer=config__pb2.Post.FromString,
                )
        self.CreateComment = channel.unary_unary(
                '/RedditService/CreateComment',
                request_serializer=config__pb2.CreateCommentRequest.SerializeToString,
                response_deserializer=config__pb2.Comment.FromString,
                )
        self.VoteComment = channel.unary_unary(
                '/RedditService/VoteComment',
                request_serializer=config__pb2.VoteCommentRequest.SerializeToString,
                response_deserializer=config__pb2.Comment.FromString,
                )
        self.GetMostUpvotedComments = channel.unary_unary(
                '/RedditService/GetMostUpvotedComments',
                request_serializer=config__pb2.GetMostUpvotedCommentsRequest.SerializeToString,
                response_deserializer=config__pb2.GetMostUpvotedCommentsResponse.FromString,
                )
        self.ExpandCommentBranch = channel.unary_unary(
                '/RedditService/ExpandCommentBranch',
                request_serializer=config__pb2.ExpandCommentBranchRequest.SerializeToString,
                response_deserializer=config__pb2.ExpandCommentBranchResponse.FromString,
                )
        self.MonitorUpdates = channel.unary_stream(
                '/RedditService/MonitorUpdates',
                request_serializer=config__pb2.MonitorUpdatesRequest.SerializeToString,
                response_deserializer=config__pb2.MonitorUpdatesResponse.FromString,
                )


class RedditServiceServicer(object):
    """Service definition
    """

    def CreatePost(self, request, context):
        """Create a Post
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VotePost(self, request, context):
        """Upvote or downvote a Post
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPost(self, request, context):
        """Retrieve Post content
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateComment(self, request, context):
        """Create a Comment
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VoteComment(self, request, context):
        """Upvote or downvote a Comment
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMostUpvotedComments(self, request, context):
        """Retrieve N most upvoted comments under a post
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExpandCommentBranch(self, request, context):
        """Expand a comment branch
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MonitorUpdates(self, request, context):
        """Extra credit: Monitor updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RedditServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePost': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePost,
                    request_deserializer=config__pb2.Post.FromString,
                    response_serializer=config__pb2.Post.SerializeToString,
            ),
            'VotePost': grpc.unary_unary_rpc_method_handler(
                    servicer.VotePost,
                    request_deserializer=config__pb2.VotePostRequest.FromString,
                    response_serializer=config__pb2.Post.SerializeToString,
            ),
            'GetPost': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPost,
                    request_deserializer=config__pb2.GetPostRequest.FromString,
                    response_serializer=config__pb2.Post.SerializeToString,
            ),
            'CreateComment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateComment,
                    request_deserializer=config__pb2.CreateCommentRequest.FromString,
                    response_serializer=config__pb2.Comment.SerializeToString,
            ),
            'VoteComment': grpc.unary_unary_rpc_method_handler(
                    servicer.VoteComment,
                    request_deserializer=config__pb2.VoteCommentRequest.FromString,
                    response_serializer=config__pb2.Comment.SerializeToString,
            ),
            'GetMostUpvotedComments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMostUpvotedComments,
                    request_deserializer=config__pb2.GetMostUpvotedCommentsRequest.FromString,
                    response_serializer=config__pb2.GetMostUpvotedCommentsResponse.SerializeToString,
            ),
            'ExpandCommentBranch': grpc.unary_unary_rpc_method_handler(
                    servicer.ExpandCommentBranch,
                    request_deserializer=config__pb2.ExpandCommentBranchRequest.FromString,
                    response_serializer=config__pb2.ExpandCommentBranchResponse.SerializeToString,
            ),
            'MonitorUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.MonitorUpdates,
                    request_deserializer=config__pb2.MonitorUpdatesRequest.FromString,
                    response_serializer=config__pb2.MonitorUpdatesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RedditService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RedditService(object):
    """Service definition
    """

    @staticmethod
    def CreatePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RedditService/CreatePost',
            config__pb2.Post.SerializeToString,
            config__pb2.Post.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VotePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RedditService/VotePost',
            config__pb2.VotePostRequest.SerializeToString,
            config__pb2.Post.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RedditService/GetPost',
            config__pb2.GetPostRequest.SerializeToString,
            config__pb2.Post.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RedditService/CreateComment',
            config__pb2.CreateCommentRequest.SerializeToString,
            config__pb2.Comment.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VoteComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RedditService/VoteComment',
            config__pb2.VoteCommentRequest.SerializeToString,
            config__pb2.Comment.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMostUpvotedComments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RedditService/GetMostUpvotedComments',
            config__pb2.GetMostUpvotedCommentsRequest.SerializeToString,
            config__pb2.GetMostUpvotedCommentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExpandCommentBranch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RedditService/ExpandCommentBranch',
            config__pb2.ExpandCommentBranchRequest.SerializeToString,
            config__pb2.ExpandCommentBranchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MonitorUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/RedditService/MonitorUpdates',
            config__pb2.MonitorUpdatesRequest.SerializeToString,
            config__pb2.MonitorUpdatesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
